# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_date']},
        ),
        migrations.AddField(
            model_name='post',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
